import { NextRequest, NextResponse } from "next/server";
import { readVoiceSample } from "@/lib/tts/samples";
import { findEveraiVoice } from "@/lib/tts/voices";

export const runtime = "nodejs";

type Ctx = { params: Promise<{ code: string }> };

/** Public: play a cached voice sample generated by admin. */
export async function GET(_req: NextRequest, ctx: Ctx) {
  const { code: raw } = await ctx.params;
  const code = decodeURIComponent(raw || "").trim();
  if (!code || !findEveraiVoice(code)) {
    return NextResponse.json({ error: "Không tìm thấy giọng." }, { status: 404 });
  }
  const buf = await readVoiceSample(code);
  if (!buf) {
    return NextResponse.json(
      { error: "Chưa có mẫu nghe thử cho giọng này." },
      { status: 404 },
    );
  }
  return new NextResponse(new Uint8Array(buf), {
    status: 200,
    headers: {
      "Content-Type": "audio/mpeg",
      "Cache-Control": "public, max-age=3600",
      "Content-Length": String(buf.length),
    },
  });
}
